### ISSUE TITLE
Don't show 'Custom Fields' section on Database edit page

### ISSUE THREAD

**Issue by boonebgorges** [rjbaniel/beyond-citation#1]
I think you can do this by calling `remove_meta_box()`. See http://stackoverflow.com/a/4105644

**Comment by rjbaniel** [comment]
Just had to remove support for custom fields from the register_post_type args. Don't know why I included it in the first place! Here's the commit: https://github.com/rjbaniel/beyond-citation/commit/f04de6ac9e44c8a5919fed27de6850046e200353
